"""
Test to verify that hardcoded credentials have been removed
and that environment variable configuration works correctly.
"""
import os
import pytest
from pathlib import Path
from unittest import mock


def test_no_hardcoded_credentials_in_config():
    """Verify that config.py doesn't contain hardcoded credentials"""
    config_path = Path('app/core/config.py')
    if not config_path.exists():
        pytest.skip("config.py not found in expected location")
    
    config_content = config_path.read_text()
    
    # These credentials should not appear in the code
    assert 'Picano78@gmail.com' not in config_content, "Hardcoded email found in config.py"
    assert 'Simone78' not in config_content, "Hardcoded password found in config.py"
    assert '_default_admin_email' not in config_content, "Default admin email variable found in config.py"
    assert '_default_admin_password' not in config_content, "Default admin password variable found in config.py"


def test_no_hardcoded_credentials_in_seed():
    """Verify that seed.py doesn't contain hardcoded credentials"""
    seed_path = Path('app/core/seed.py')
    if not seed_path.exists():
        pytest.skip("seed.py not found in expected location")
    
    seed_content = seed_path.read_text()
    
    # These credentials should not appear in the code
    assert 'Picano78@gmail.com' not in seed_content, "Hardcoded email found in seed.py"
    assert 'Simone78' not in seed_content, "Hardcoded password found in seed.py"
    assert 'DEFAULT_SUPERADMIN_EMAIL' not in seed_content, "DEFAULT_SUPERADMIN_EMAIL constant found in seed.py"
    assert 'DEFAULT_SUPERADMIN_PASSWORD' not in seed_content, "DEFAULT_SUPERADMIN_PASSWORD constant found in seed.py"


def test_config_loads_from_environment():
    """Test that config properly loads credentials from environment variables"""
    with mock.patch.dict(os.environ, {
        'SUPERADMIN_EMAIL': 'test@example.com',
        'SUPERADMIN_PASSWORD': 'TestPassword123!',
        'APP_ENV': 'development'
    }):
        # Import the config module with mocked environment
        import importlib
        import sys
        
        # Remove the module from cache to force reload
        if 'app.core.config' in sys.modules:
            del sys.modules['app.core.config']
        
        from app.core import config
        
        # Verify that credentials are loaded from environment
        assert config.Config.SUPERADMIN_EMAIL == 'test@example.com'
        assert config.Config.SUPERADMIN_PASSWORD == 'TestPassword123!'


def test_production_mode_requires_credentials():
    """Test that production mode fails if credentials are not set"""
    with mock.patch.dict(os.environ, {
        'APP_ENV': 'production',
        'SECRET_KEY': 'test-secret-key-for-production',
        'DATABASE_URL': 'postgresql://user:pass@localhost:5432/sonacip_test',
    }, clear=True):
        # Remove credentials from environment
        os.environ.pop('SUPERADMIN_EMAIL', None)
        os.environ.pop('SUPERADMIN_PASSWORD', None)

        import importlib
        import sys

        # Remove the module from cache to force reload
        if 'app.core.config' in sys.modules:
            del sys.modules['app.core.config']

        from app.core import config as config_mod

        # Credentials should be None when not set in environment
        assert config_mod.Config.SUPERADMIN_EMAIL is None
        assert config_mod.Config.SUPERADMIN_PASSWORD is None

        # ProductionConfig.validate_config should log a warning (not raise)
        # because seed.py handles generating default credentials
        config_mod.ProductionConfig.validate_config()


def test_development_mode_allows_missing_credentials():
    """Test that development mode allows missing credentials (will generate random ones)"""
    with mock.patch.dict(os.environ, {
        'APP_ENV': 'development',
    }, clear=True):
        # Remove credentials from environment
        os.environ.pop('SUPERADMIN_EMAIL', None)
        os.environ.pop('SUPERADMIN_PASSWORD', None)
        
        # Import should succeed in development mode
        import importlib
        import sys
        
        # Remove the module from cache to force reload
        if 'app.core.config' in sys.modules:
            del sys.modules['app.core.config']
        
        from app.core import config
        
        # Credentials should be None (will be generated by seed)
        assert config.Config.SUPERADMIN_EMAIL is None
        assert config.Config.SUPERADMIN_PASSWORD is None


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
