"""add_missing_tables_complete_migrations

Revision ID: 1221257e6c86
Revises: d2f4a6c8e0b1
Create Date: 2026-02-11 21:49:17.134998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1221257e6c86'
down_revision = 'd2f4a6c8e0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('default_size', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_key')
    )
    op.create_table('athlete_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('sport_type', sa.String(length=50), nullable=True),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete_stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athlete_stat_society_id'), ['society_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_stat_user_id'), ['user_id'], unique=False)

    op.create_table('document_folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['document_folder.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_folder_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_folder_society_id'), ['society_id'], unique=False)

    op.create_table('email_confirmation_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('token_expiry_hours', sa.Integer(), nullable=True),
    sa.Column('max_resends', sa.Integer(), nullable=True),
    sa.Column('email_subject', sa.String(length=255), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('auto_confirm_existing', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_society_id'), ['society_id'], unique=False)

    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('multiple_choice', sa.Boolean(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_society_id'), ['society_id'], unique=False)

    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.String(length=255), nullable=True),
    sa.Column('auth_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='uq_push_subscription_user_endpoint')
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('stat_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport_type', sa.String(length=50), nullable=True),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.Column('fields', sa.Text(), nullable=True),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stat_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_template_society_id'), ['society_id'], unique=False)

    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_user_id'), ['user_id'], unique=False)

    op.create_table('user_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badge_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badge_user_id'), ['user_id'], unique=False)

    op.create_table('user_dashboard_layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'widget_key', name='uq_user_dashboard_layout')
    )
    with op.batch_alter_table('user_dashboard_layout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dashboard_layout_user_id'), ['user_id'], unique=False)

    op.create_table('user_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('events_attended', sa.Integer(), nullable=True),
    sa.Column('login_streak', sa.Integer(), nullable=True),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('badges_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_points_user_id'), ['user_id'], unique=True)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folder.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_society_id'), ['society_id'], unique=False)

    op.create_table('fee_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_receipt_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fee_id'], ['society_fee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_payment_fee_id'), ['fee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_payment_user_id'), ['user_id'], unique=False)

    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_membership')
    )
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_membership_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_membership_user_id'), ['user_id'], unique=False)

    op.create_table('group_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_message_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_user_id'), ['user_id'], unique=False)

    op.create_table('poll_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('votes_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_option_poll_id'), ['poll_id'], unique=False)

    op.create_table('story_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'viewer_id', name='uq_story_view')
    )
    with op.batch_alter_table('story_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_view_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_view_viewer_id'), ['viewer_id'], unique=False)

    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['poll_option.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'user_id', 'option_id', name='uq_poll_vote')
    )
    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_vote_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_vote_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_vote_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ad_campaign', schema=None) as batch_op:
        batch_op.drop_index('ix_ad_campaign_society_id')

    with op.batch_alter_table('ad_event', schema=None) as batch_op:
        batch_op.drop_index('ix_ad_event_kind')

    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.drop_constraint('uq_addon_slug', type_='unique')
        batch_op.drop_index('ix_addon_slug')
        batch_op.create_index(batch_op.f('ix_addon_slug'), ['slug'], unique=True)

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index('ix_coupon_code')
        batch_op.create_index(batch_op.f('ix_coupon_code'), ['code'], unique=True)

    with op.batch_alter_table('crm_pipeline', schema=None) as batch_op:
        batch_op.drop_constraint('uq_crm_pipeline_society', type_='unique')
        batch_op.drop_index('ix_crm_pipeline_society_id')
        batch_op.create_index(batch_op.f('ix_crm_pipeline_society_id'), ['society_id'], unique=True)

    with op.batch_alter_table('marketplace_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_promoted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('promotion_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_marketplace_listing_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listing_is_promoted'), ['is_promoted'], unique=False)

    with op.batch_alter_table('marketplace_package', schema=None) as batch_op:
        batch_op.drop_constraint('uq_marketplace_package_slug', type_='unique')
        batch_op.drop_index('ix_marketplace_package_slug')
        batch_op.create_index(batch_op.f('ix_marketplace_package_slug'), ['slug'], unique=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_id')
        batch_op.drop_index('ix_notification_user_unread')

    with op.batch_alter_table('platform_feature', schema=None) as batch_op:
        batch_op.drop_constraint('uq_platform_feature_key', type_='unique')
        batch_op.drop_index('ix_platform_feature_key')
        batch_op.create_index(batch_op.f('ix_platform_feature_key'), ['key'], unique=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('audience',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'"))
        batch_op.drop_index('ix_post_audience')
        batch_op.drop_index('ix_post_post_type')
        batch_op.drop_index('ix_post_society_id')
        batch_op.drop_index('ix_post_target_user_id')

    with op.batch_alter_table('profile_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('display_order')

    with op.batch_alter_table('promotion_tier', schema=None) as batch_op:
        batch_op.drop_constraint('uq_promotion_tier_slug', type_='unique')
        batch_op.drop_index('ix_promotion_tier_slug')
        batch_op.create_index(batch_op.f('ix_promotion_tier_slug'), ['slug'], unique=True)

    with op.batch_alter_table('tournament_match', schema=None) as batch_op:
        batch_op.drop_index('ix_tournament_match_match_date')
        batch_op.drop_index('ix_tournament_match_status')
        batch_op.drop_index('ix_tournament_match_tournament_id')

    with op.batch_alter_table('whatsapp_template', schema=None) as batch_op:
        batch_op.drop_constraint('uq_whatsapp_template_key', type_='unique')
        batch_op.drop_index('ix_whatsapp_template_key')
        batch_op.create_index(batch_op.f('ix_whatsapp_template_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_template_key'))
        batch_op.create_index('ix_whatsapp_template_key', ['key'], unique=False)
        batch_op.create_unique_constraint('uq_whatsapp_template_key', ['key'])

    with op.batch_alter_table('tournament_match', schema=None) as batch_op:
        batch_op.create_index('ix_tournament_match_tournament_id', ['tournament_id'], unique=False)
        batch_op.create_index('ix_tournament_match_status', ['status'], unique=False)
        batch_op.create_index('ix_tournament_match_match_date', ['match_date'], unique=False)

    with op.batch_alter_table('promotion_tier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_tier_slug'))
        batch_op.create_index('ix_promotion_tier_slug', ['slug'], unique=False)
        batch_op.create_unique_constraint('uq_promotion_tier_slug', ['slug'])

    with op.batch_alter_table('profile_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.INTEGER(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('order')
        batch_op.drop_column('is_required')
        batch_op.drop_column('name_en')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_target_user_id', ['target_user_id'], unique=False)
        batch_op.create_index('ix_post_society_id', ['society_id'], unique=False)
        batch_op.create_index('ix_post_post_type', ['post_type'], unique=False)
        batch_op.create_index('ix_post_audience', ['audience'], unique=False)
        batch_op.alter_column('audience',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'"))

    with op.batch_alter_table('platform_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_feature_key'))
        batch_op.create_index('ix_platform_feature_key', ['key'], unique=False)
        batch_op.create_unique_constraint('uq_platform_feature_key', ['key'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_unread', ['user_id', 'is_read'], unique=False)
        batch_op.create_index('ix_notification_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('marketplace_package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_package_slug'))
        batch_op.create_index('ix_marketplace_package_slug', ['slug'], unique=False)
        batch_op.create_unique_constraint('uq_marketplace_package_slug', ['slug'])

    with op.batch_alter_table('marketplace_listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_listing_is_promoted'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listing_expires_at'))
        batch_op.drop_column('promotion_expires_at')
        batch_op.drop_column('is_promoted')
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('crm_pipeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_pipeline_society_id'))
        batch_op.create_index('ix_crm_pipeline_society_id', ['society_id'], unique=False)
        batch_op.create_unique_constraint('uq_crm_pipeline_society', ['society_id'])

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_code'))
        batch_op.create_index('ix_coupon_code', ['code'], unique=False)

    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addon_slug'))
        batch_op.create_index('ix_addon_slug', ['slug'], unique=False)
        batch_op.create_unique_constraint('uq_addon_slug', ['slug'])

    with op.batch_alter_table('ad_event', schema=None) as batch_op:
        batch_op.create_index('ix_ad_event_kind', ['kind'], unique=False)

    with op.batch_alter_table('ad_campaign', schema=None) as batch_op:
        batch_op.create_index('ix_ad_campaign_society_id', ['society_id'], unique=False)

    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_vote_user_id'))
        batch_op.drop_index(batch_op.f('ix_poll_vote_poll_id'))
        batch_op.drop_index(batch_op.f('ix_poll_vote_option_id'))

    op.drop_table('poll_vote')
    with op.batch_alter_table('story_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_view_viewer_id'))
        batch_op.drop_index(batch_op.f('ix_story_view_story_id'))

    op.drop_table('story_view')
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_option_poll_id'))

    op.drop_table('poll_option')
    with op.batch_alter_table('group_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_message_group_id'))

    op.drop_table('group_message')
    with op.batch_alter_table('group_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_membership_group_id'))

    op.drop_table('group_membership')
    with op.batch_alter_table('fee_payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_payment_user_id'))
        batch_op.drop_index(batch_op.f('ix_fee_payment_fee_id'))

    op.drop_table('fee_payment')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_society_id'))
        batch_op.drop_index(batch_op.f('ix_document_folder_id'))

    op.drop_table('document')
    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_points_user_id'))

    op.drop_table('user_points')
    with op.batch_alter_table('user_dashboard_layout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_layout_user_id'))

    op.drop_table('user_dashboard_layout')
    with op.batch_alter_table('user_badge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badge_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badge_badge_id'))

    op.drop_table('user_badge')
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_user_id'))

    op.drop_table('story')
    with op.batch_alter_table('stat_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_template_society_id'))

    op.drop_table('stat_template')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_society_id'))
        batch_op.drop_index(batch_op.f('ix_poll_creator_id'))

    op.drop_table('poll')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_society_id'))
        batch_op.drop_index(batch_op.f('ix_group_creator_id'))

    op.drop_table('group')
    op.drop_table('email_confirmation_setting')
    with op.batch_alter_table('document_folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_folder_society_id'))
        batch_op.drop_index(batch_op.f('ix_document_folder_parent_id'))

    op.drop_table('document_folder')
    with op.batch_alter_table('athlete_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_athlete_stat_society_id'))

    op.drop_table('athlete_stat')
    op.drop_table('dashboard_widget')
    op.drop_table('contact_message')
    op.drop_table('badge')
    # ### end Alembic commands ###
