"""society memberships and post scoping

Revision ID: 78b7221f7c74
Revises: ff738ea962ee
Create Date: 2026-02-01 07:40:12.693777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b7221f7c74'
down_revision = 'ff738ea962ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('society_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['society.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'user_id', name='uq_society_membership')
    )
    with op.batch_alter_table('society_membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_society_membership_society_id'), ['society_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_society_membership_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience', sa.String(length=20), nullable=False, server_default='public'))
        batch_op.add_column(sa.Column('society_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_target_user', 'user', ['target_user_id'], ['id'])
        batch_op.create_foreign_key('fk_post_society', 'society', ['society_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_society', type_='foreignkey')
        batch_op.drop_constraint('fk_post_target_user', type_='foreignkey')
        batch_op.drop_column('target_user_id')
        batch_op.drop_column('society_id')
        batch_op.drop_column('audience')

    with op.batch_alter_table('society_membership', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_society_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_society_membership_society_id'))

    op.drop_table('society_membership')
    # ### end Alembic commands ###
