"""add_platform_feature_table

Revision ID: b8ccb2eccc31
Revises: 0a2a8dacd6c8
Create Date: 2026-02-06 08:15:54.516208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ccb2eccc31'
down_revision = '0a2a8dacd6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_photos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_videos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_setting', schema=None) as batch_op:
        batch_op.drop_column('allow_videos')
        batch_op.drop_column('allow_photos')

    # ### end Alembic commands ###
