"""add_marketplace_listing_table

Revision ID: fcec1bf08c43
Revises: b8ccb2eccc31
Create Date: 2026-02-06 08:43:53.377574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcec1bf08c43'
down_revision = 'b8ccb2eccc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('image_1', sa.String(length=300), nullable=True),
    sa.Column('image_2', sa.String(length=300), nullable=True),
    sa.Column('image_3', sa.String(length=300), nullable=True),
    sa.Column('image_4', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['society_id'], ['society.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketplace_listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_listing_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listing_society_id'), ['society_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listing_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listing_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_listing_user_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listing_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listing_society_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listing_created_at'))

    op.drop_table('marketplace_listing')
    # ### end Alembic commands ###
